version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  app:
    container_name: app
    restart: always
    build: .
    env_file: .env
    environment:
      - PORT=${PORT}
      - TOKEN_KEY=${TOKEN_KEY}
      - MONGO_URI=${MONGO_URI}
    ports:
      - 8080:8080
    external_links:
      - mongo
    depends_on:
      - mongo